AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple HTML web application on EC2 using Apache

Parameters:
  KeyName:
    Type: String
    Default: Final
    Description: Name of an existing EC2 KeyPair for SSH

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0953476d60561c955  # Amazon Linux 2023 (us-east-1)
      KeyName: !Ref KeyName
      SubnetId: subnet-0d32f470f7510076b  # Terraform public subnet (us-east-1a)
      SecurityGroupIds:
        - sg-0f549043e6f661f8f            # Terraform security group
      Tags:
        - Key: Name
          Value: WebAppInstance
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<!DOCTYPE html>
          <html>
          <head><title>My Web App</title></head>
          <body>
            <h1>Hello from EC2!</h1>
            <p>This web app was deployed via CloudFormation.</p>
          </body>
          </html>" > /var/www/html/index.html
